; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mqtt
src_dir = src

[env]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0

[env:mqtt]
build_src_filter = 
	-<*>
	+<mqtt.cpp>
build_flags = -I Examples/mqtt
lib_deps = knolleary/PubSubClient@^2.8

[env:remote_do]
build_src_filter = 
	-<*>
	+<remote_do.cpp>
build_flags = -I Examples/remote_DO

[env:wifi_portal_mqtt]
build_src_filter = 
	-<*>
	+<wifi_portal_mqtt.cpp>
build_flags = 
	-I Examples/wifi_portal_mqtt
	-I Examples/mqtt
lib_deps = knolleary/PubSubClient@^2.8
