# AQS-X01 @ BytesOnTheRocks

# Modbus Registers

CO2_REG_NUM = 0
CO2_AVG_REG_NUM = 1
TEMP_REG_NUM = 2
HUM_REG_NUM = 3

TVOC_REG_NUM = 4
ECO2_REG_NUM = 5
TVOC_AVG_REG_NUM = 6
ECO2_AVG_REG_NUM = 7
TVOC_BASE_REG_NUM = 8
ECO2_BASE_REG_NUM = 9

ETHANOL_BASE_REG_NUM = 10
H2RAW_BASE_REG_NUM = 11

FW_VERSION_REG_NUM = (12,)
