#AQS-X01 @ BytesOnTheRocks

#Modbus Registers related to AQS-X01 configuration


GREENAMBER_THRESHOLD_REG_NUM          = 0
AMBERRED_THRESHOLD_REG_NUM            = 1
SLAVE_ADDRESS_REG_NUM                 = 2
MODBUS_RTU_SERIAL_BAUDRATE_REG_NUM    = 3
MODBUS_RTU_SERIAL_CONF_REG_NUM        = 4
SHT31_TEMPERATURE_OFFSET_REG_NUM      = 5
ESP8266_HOLD_RESET_PERIOD_REG_NUM     = 6